title: The History of Rome
description: A podcast tracing the history of the Roman Empire, beginning with Aeneas's arrival in Italy and ending with the exile of Romulus Augustulus, last Emperor of the Western Roman Empire.
permalink: pretty

sass:
  sass_dir: lib/css
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
      permalink: /episode/:slug/
